import { format } from "date-fns";
export const APIDictionary = {
    EUR: {
        Equities: {
            symbols: [
                { value: "VGWL", exchange: "XETRA" },
                { value: "SXR8", exchange: "XETRA" },
                { value: "EUNL", exchange: "XETRA" },
                { value: "IS3N", exchange: "XETRA" },
                { value: "EUNL", exchange: "XETRA" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        Currencies: {
            symbols: [
                { value: "EURUSD", exchange: "FOREX" },
                { value: "EURGBP", exchange: "FOREX" },
                { value: "EURCHF", exchange: "FOREX" },
                { value: "EURJPY", exchange: "FOREX" },
                { value: "EURPLN", exchange: "FOREX" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        "Bond Yields": {
            symbols: [
                { value: "DE3M", exchange: "GBOND" },
                { value: "FR3M", exchange: "GBOND" },
                { value: "IT3M", exchange: "GBOND" },
                { value: "ES3M", exchange: "GBOND" },
                { value: "DE1Y", exchange: "GBOND" },
                { value: "FR1Y", exchange: "GBOND" },
                { value: "IT1Y", exchange: "GBOND" },
                { value: "ES1Y", exchange: "GBOND" },
                { value: "DE3Y", exchange: "GBOND" },
                { value: "FR3Y", exchange: "GBOND" },
                { value: "IT3Y", exchange: "GBOND" },
                { value: "ES3Y", exchange: "GBOND" },
                { value: "DE5Y", exchange: "GBOND" },
                { value: "FR5Y", exchange: "GBOND" },
                { value: "IT5Y", exchange: "GBOND" },
                { value: "ES5Y", exchange: "GBOND" },
                { value: "DE10Y", exchange: "GBOND" },
                { value: "FR10Y", exchange: "GBOND" },
                { value: "IT10Y", exchange: "GBOND" },
                { value: "ES10Y", exchange: "GBOND" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
    },
    USD: {
        Equities: {
            symbols: [
                { value: "VWRA", exchange: "LSE" },
                { value: "VXUS", exchange: "US" },
                { value: "VUSD", exchange: "LSE" },
                { value: "IWDA", exchange: "LSE" },
                { value: "EIMI", exchange: "LSE" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        Currencies: {
            symbols: [
                { value: "USDEUR", exchange: "FOREX" },
                { value: "USDGBP", exchange: "FOREX" },
                { value: "USDCHF", exchange: "FOREX" },
                { value: "USDJPY", exchange: "FOREX" },
                { value: "USDPLN", exchange: "FOREX" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        "Bond Yields": {
            symbols: [
                { value: "US3M", exchange: "GBOND" },
                { value: "CA3M", exchange: "GBOND" },
                { value: "DE3M", exchange: "GBOND" },
                { value: "JP3M", exchange: "GBOND" },
                { value: "US1Y", exchange: "GBOND" },
                { value: "CA1Y", exchange: "GBOND" },
                { value: "DE1Y", exchange: "GBOND" },
                { value: "JP1Y", exchange: "GBOND" },
                { value: "US3Y", exchange: "GBOND" },
                { value: "CA3Y", exchange: "GBOND" },
                { value: "DE3Y", exchange: "GBOND" },
                { value: "JP3Y", exchange: "GBOND" },
                { value: "US5Y", exchange: "GBOND" },
                { value: "CA5Y", exchange: "GBOND" },
                { value: "DE5Y", exchange: "GBOND" },
                { value: "JP5Y", exchange: "GBOND" },
                { value: "US10Y", exchange: "GBOND" },
                { value: "CA10Y", exchange: "GBOND" },
                { value: "DE10Y", exchange: "GBOND" },
                { value: "JP10Y", exchange: "GBOND" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
    },
    GBP: {
        Equities: {
            symbols: [
                { value: "VWRP", exchange: "LSE" },
                { value: "CSP1", exchange: "LSE" },
                { value: "SWDA", exchange: "LSE" },
                { value: "EMIM", exchange: "LSE" },
                { value: "CUKX", exchange: "LSE" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        Currencies: {
            symbols: [
                { value: "GBPUSD", exchange: "FOREX" },
                { value: "GBPEUR", exchange: "FOREX" },
                { value: "GBPCHF", exchange: "FOREX" },
                { value: "GBPJPY", exchange: "FOREX" },
                { value: "GBPPLN", exchange: "FOREX" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
        "Bond Yields": {
            symbols: [
                { value: "UK3M", exchange: "GBOND" },
                { value: "US3M", exchange: "GBOND" },
                { value: "DE3M", exchange: "GBOND" },
                { value: "FR3M", exchange: "GBOND" },
                { value: "UK1Y", exchange: "GBOND" },
                { value: "US1Y", exchange: "GBOND" },
                { value: "DE1Y", exchange: "GBOND" },
                { value: "FR1Y", exchange: "GBOND" },
                { value: "UK3Y", exchange: "GBOND" },
                { value: "US3Y", exchange: "GBOND" },
                { value: "DE3Y", exchange: "GBOND" },
                { value: "FR3Y", exchange: "GBOND" },
                { value: "UK5Y", exchange: "GBOND" },
                { value: "US5Y", exchange: "GBOND" },
                { value: "DE5Y", exchange: "GBOND" },
                { value: "FR5Y", exchange: "GBOND" },
                { value: "UK10Y", exchange: "GBOND" },
                { value: "US10Y", exchange: "GBOND" },
                { value: "DE10Y", exchange: "GBOND" },
                { value: "FR10Y", exchange: "GBOND" },
            ],
            fromDate: "1970-01-01",
            toDate: format(new Date(), "yyyy-MM-dd"),
        },
    },
};
//# sourceMappingURL=utils.js.map