export const EquityData = [
    {
        metricAlias: "Global Equities",
        metric: "VGWL",
        time: "MTD",
        value: 0.9521187390855249,
        exchange: "XETRA",
    },
    {
        metricAlias: "Global Equities",
        metric: "VGWL",
        time: "YTD",
        value: 8.478638267467758,
        exchange: "XETRA",
    },
    {
        metricAlias: "Global Equities",
        metric: "VGWL",
        time: "1Y",
        value: 24.640296229150003,
        exchange: "XETRA",
    },
    {
        metricAlias: "Global Equities",
        metric: "VGWL",
        time: "5Y",
        value: 76.24528022394941,
        exchange: "XETRA",
    },
    {
        metricAlias: "Global Equities",
        metric: "VGWL",
        time: "WTD",
        value: 1.7246959818745091,
        exchange: "XETRA",
    },
    {
        metricAlias: "US Large Caps",
        metric: "SXR8",
        time: "MTD",
        value: 1.057934508816121,
        exchange: "XETRA",
    },
    {
        metricAlias: "US Large Caps",
        metric: "SXR8",
        time: "YTD",
        value: 10.416345582245317,
        exchange: "XETRA",
    },
    {
        metricAlias: "US Large Caps",
        metric: "SXR8",
        time: "1Y",
        value: 30.660205304569853,
        exchange: "XETRA",
    },
    {
        metricAlias: "US Large Caps",
        metric: "SXR8",
        time: "5Y",
        value: 103.93639949575049,
        exchange: "XETRA",
    },
    {
        metricAlias: "US Large Caps",
        metric: "SXR8",
        time: "WTD",
        value: 1.6375501601070048,
        exchange: "XETRA",
    },
    {
        metricAlias: "Developed Markets",
        metric: "EUNL",
        time: "MTD",
        value: -1.9945105215004508,
        exchange: "XETRA",
    },
    {
        metricAlias: "Developed Markets",
        metric: "EUNL",
        time: "YTD",
        value: 1.689766470476553,
        exchange: "XETRA",
    },
    {
        metricAlias: "Developed Markets",
        metric: "EUNL",
        time: "1Y",
        value: 14.87399463806971,
        exchange: "XETRA",
    },
    {
        metricAlias: "Developed Markets",
        metric: "EUNL",
        time: "5Y",
        value: 42.902881536819656,
        exchange: "XETRA",
    },
    {
        metricAlias: "Developed Markets",
        metric: "EUNL",
        time: "WTD",
        value: -1.1078286558345538,
        exchange: "XETRA",
    },
    {
        metricAlias: "Emerging Markets",
        metric: "IS3N",
        time: "MTD",
        value: 0.22249941003943952,
        exchange: "XETRA",
    },
    {
        metricAlias: "Emerging Markets",
        metric: "IS3N",
        time: "YTD",
        value: 3.480803369417661,
        exchange: "XETRA",
    },
    {
        metricAlias: "Emerging Markets",
        metric: "IS3N",
        time: "1Y",
        value: 11.725356082528457,
        exchange: "XETRA",
    },
    {
        metricAlias: "Emerging Markets",
        metric: "IS3N",
        time: "5Y",
        value: 18.63128491620112,
        exchange: "XETRA",
    },
    {
        metricAlias: "Emerging Markets",
        metric: "IS3N",
        time: "WTD",
        value: 1.3500153410834241,
        exchange: "XETRA",
    },
];
export const CurrencyData = [
    {
        metric: "EURUSD",
        period: "Level",
        exchange: "FOREX",
        value: 1.0935,
    },
    {
        metric: "EURUSD",
        period: "YTD",
        value: 1.1036,
        exchange: "FOREX",
    },
    {
        metric: "EURUSD",
        period: "1Y",
        value: 1.560323209807739,
        exchange: "FOREX",
    },
    {
        metric: "EURUSD",
        period: "5Y",
        value: -3.8512265892904303,
        exchange: "FOREX",
    },
    {
        metric: "EURGBP",
        period: "Level",
        exchange: "FOREX",
        value: 0.8543,
    },
    {
        metric: "EURGBP",
        period: "YTD",
        value: 0.867,
        exchange: "FOREX",
    },
    {
        metric: "EURGBP",
        period: "1Y",
        value: -3.0966424682395757,
        exchange: "FOREX",
    },
    {
        metric: "EURGBP",
        period: "5Y",
        value: -1.5443125504206612,
        exchange: "FOREX",
    },
    {
        metric: "EURCHF",
        period: "Level",
        exchange: "FOREX",
        value: 0.9678,
    },
    {
        metric: "EURCHF",
        period: "YTD",
        value: 0.9287,
        exchange: "FOREX",
    },
    {
        metric: "EURCHF",
        period: "1Y",
        value: -2.527948433880553,
        exchange: "FOREX",
    },
    {
        metric: "EURCHF",
        period: "5Y",
        value: -14.20212765957446,
        exchange: "FOREX",
    },
    {
        metric: "EURJPY",
        period: "Level",
        exchange: "FOREX",
        value: 164.6,
    },
    {
        metric: "EURJPY",
        period: "YTD",
        value: 155.67,
        exchange: "FOREX",
    },
    {
        metric: "EURJPY",
        period: "1Y",
        value: 15.371136188406819,
        exchange: "FOREX",
    },
    {
        metric: "EURJPY",
        period: "5Y",
        value: 30.634920634920633,
        exchange: "FOREX",
    },
    {
        metric: "EURPLN",
        period: "Level",
        exchange: "FOREX",
        value: 4.3131,
    },
    {
        metric: "EURPLN",
        period: "YTD",
        value: 4.3394,
        exchange: "FOREX",
    },
    {
        metric: "EURPLN",
        period: "1Y",
        value: -7.8633683670853465,
        exchange: "FOREX",
    },
    {
        metric: "EURPLN",
        period: "5Y",
        value: 0.6252478827893662,
        exchange: "FOREX",
    },
];
export const BondYieldsData = [
    {
        country: "DE",
        duration: "3 Month",
        value: 3.755,
        metric: "DE3M",
        exchange: "GBOND",
    },
    {
        country: "FR",
        duration: "3 Month",
        value: 3.839,
        metric: "FR3M",
        exchange: "GBOND",
    },
    {
        country: "IT",
        duration: "3 Month",
        value: 3.701,
        metric: "IT3M",
        exchange: "GBOND",
    },
    {
        country: "ES",
        duration: "3 Month",
        value: 3.766,
        metric: "ES3M",
        exchange: "GBOND",
    },
    {
        country: "DE",
        duration: "1 Year",
        value: 3.4432,
        metric: "DE1Y",
        exchange: "GBOND",
    },
    {
        country: "FR",
        duration: "1 Year",
        value: 3.505,
        metric: "FR1Y",
        exchange: "GBOND",
    },
    {
        country: "IT",
        duration: "1 Year",
        value: 3.6094,
        metric: "IT1Y",
        exchange: "GBOND",
    },
    {
        country: "ES",
        duration: "1 Year",
        value: 3.466,
        metric: "ES1Y",
        exchange: "GBOND",
    },
    {
        country: "DE",
        duration: "3 Years",
        value: 2.6049,
        metric: "DE3Y",
        exchange: "GBOND",
    },
    {
        country: "FR",
        duration: "3 Years",
        value: 2.7879,
        metric: "FR3Y",
        exchange: "GBOND",
    },
    {
        country: "IT",
        duration: "3 Years",
        value: 3.1961,
        metric: "IT3Y",
        exchange: "GBOND",
    },
    {
        country: "ES",
        duration: "3 Years",
        value: 2.997,
        metric: "ES3Y",
        exchange: "GBOND",
    },
    {
        country: "DE",
        duration: "5 Years",
        value: 2.449,
        metric: "DE5Y",
        exchange: "GBOND",
    },
    {
        country: "FR",
        duration: "5 Years",
        value: 2.721,
        metric: "FR5Y",
        exchange: "GBOND",
    },
    {
        country: "IT",
        duration: "5 Years",
        value: 3.433,
        metric: "IT5Y",
        exchange: "GBOND",
    },
    {
        country: "ES",
        duration: "5 Years",
        value: 3.015,
        metric: "ES5Y",
        exchange: "GBOND",
    },
    {
        country: "DE",
        duration: "10 Years",
        value: 2.4366,
        metric: "DE10Y",
        exchange: "GBOND",
    },
    {
        country: "FR",
        duration: "10 Years",
        value: 2.8758,
        metric: "FR10Y",
        exchange: "GBOND",
    },
    {
        country: "IT",
        duration: "10 Years",
        value: 3.7121,
        metric: "IT10Y",
        exchange: "GBOND",
    },
    {
        country: "ES",
        duration: "10 Years",
        value: 3.2463,
        metric: "ES10Y",
        exchange: "GBOND",
    },
];
//# sourceMappingURL=dev-utils.js.map