name: CI/CD Workflowsss

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ec2-user@ec2-51-20-145-99.eu-north-1.compute.amazonaws.com
          username: maneet
          key: ${{ secrets.KEY }}
          script: whoami