name: CI/CD Workflowsss

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ec2-51-20-145-99.eu-north-1.compute.amazonaws.com
      #     username: ubuntu
      #     key: ${{ secrets.PASSWORD }}
      #     port: 22
      #     script: whoami

      - name: SSH into EC2 and deploy 
        uses: appleboy/ssh-action@master 
        with: 
          host: ec2-51-20-145-99.eu-north-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.PASSWORD }} 