name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        docker build -t testing-ci-cd:latest ./api
        docker save -o ./testing-ci-cd.tar testing-ci-cd:latest
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        scp -i github-ec2.pem testing-ci-cd.tar ${USER}@${HOST}:/home/ec2-user/
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        # scp -i github-ec2.pem testing-ci-cd.tar ${USER}@${HOST}:/home/ec2-user/
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '

        # docker stop finstat-staging-api-latest
        # docker rm finstat-staging-api-latest
        # docker load -i /home/ec2-user/finstat-staging-api.tar
        # docker run -d --name finstat-staging-api-latest -p 1025:8000 finstat-staging-api:latest
        docker ps
        '
