name: CI/CD Workflowsss

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_PEM_FILE }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: Connect to EC2 and Deploy
        run: |
          ssh -i key.pem ubuntu@ec2-51-20-145-99.eu-north-1.compute.amazonaws.com "echo Connected to EC2"