name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        docker build -t testing-ci-cd:latest ./api
        docker save -o ./testing-ci-cd.tar testing-ci-cd:latest
        echo "$PRIVATE_KEY" > github-ec2.pem
        chmod 600 github-ec2.pem
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i github-ec2.pem testing-ci-cd.tar ${USER}@${HOST}:/home/ec2-user/
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem
        chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '

        docker stop testing-ci-cd-latest || true
        docker rm -f testing-ci-cd-backup || true
        docker rename testing-ci-cd-latest testing-ci-cd-backup
        docker load -i /home/ec2-user/testing-ci-cd.tar
        docker run -d --name testing-ci-cd-latest -p 1025:8080 testing-ci-cd:latest
        docker ps -a
        '
