name: CI/CD Workflowsss

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: SSH into server and deploy
        env:
          SSH_HOST: 167.172.48.12
          SSH_USER: maneet-new
          ASSETS_DIR: wp-content/themes/mh-magazine-lite/assets
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            cd ~/public_html/$ASSETS_DIR &&
            rm -rf backupDist &&
            mv dist backupDist
          "
          scp -i ~/.ssh/id_rsa -r -o StrictHostKeyChecking=no ./fin-stat/dist2 $SSH_USER@$SSH_HOST:~/public_html/$ASSETS_DIR