name: Frontend CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
    
    - name: Print OS info, Node & Yarn versions
      run: |
        uname -a
        node -v
        yarn -v

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Create and remove backup
      env:
        PRIVATE_KEY: ${{ secrets.WORDPRESS_KEY }}
        HOST: ${{ secrets.WORDPRESS_HOST }}
        USER: ${{ secrets.WORDPRESS_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem
        chmod 600 github-ec2.pem
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
            pwd
            cd public_html/wp-content/themes/mh-magazine-lite/assets/
            # rm -rf backupDist
            # mv dist backupDist
            ls
        '
    - name: Build Frontend and Copy dist to the server
      env:
        PRIVATE_KEY: ${{ secrets.WORDPRESS_KEY }}
        HOST: ${{ secrets.WORDPRESS_HOST }}
        USER: ${{ secrets.WORDPRESS_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # yarn build
        sshpass -p "$SSH_PASSWORD" scp -r ./dist22222 ${USER}@${HOST}:~/public_html/wp-content/themes/mh-magazine-lite/assets
