name: Frontend CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
    
    - name: Print OS info, Node & Yarn versions
      run: |
        uname -a
        node -v
        yarn -v

    # - name: Build Frontend
    #   env:
    #     PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     HOST: ${{ secrets.EC2_HOST }}
    #     USER: ${{ secrets.EC2_USER }}
    #   run: |
    #     yarn build